name: SAST Checks

on:
  push:
    paths:
      - "sast/**"
  pull_request:
    paths:
      - "sast/**"

jobs:
  sast-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Semgrep Scan
        uses: semgrep/semgrep-action@v1
        with:
          config: p/security-audit

      - name: Bandit Scan
        run: |
          pip install bandit
          bandit -r ./sast -f json -o sast-results.json

      - name: Upload SAST Results
        uses: actions/upload-artifact@v3
        with:
          name: sast-results
          path: sast-results.json
