name: SAST Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit

      - name: Run Bandit scan
        run: |
          bandit -r . -c ./sast/configs/bandit.yaml -f json -o bandit-output.json || true

      - name: Check for medium and high severity issues
        if: always()
        run: |
          if [ -f bandit-output.json ]; then
            if jq -e '.results[] | select(.issue_severity == "HIGH" or .issue_severity == "MEDIUM")' bandit-output.json > /dev/null; then
              echo "Security issues found:"
              jq '.results[] | select(.issue_severity == "HIGH" or .issue_severity == "MEDIUM") | {severity: .issue_severity, file: .filename, issue: .issue_text}' bandit-output.json
              exit 1
            else
              echo "No medium or high severity issues found"
            fi
          else
            echo "Bandit output file not found"
            exit 1
          fi
