name: SAST Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit
          pip install bandit2sarif

      - name: Run Bandit scan
        run: |
          bandit -r . -f json -o bandit-results.json || true
        # The || true ensures the step doesn't fail the workflow

      - name: Convert Bandit output to SARIF
        if: always()
        run: |
          bandit2sarif -i bandit-results.json -o bandit-results.sarif

      - name: Upload Bandit results
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: bandit-results.sarif

      - name: Check Bandit results
        run: |
          if grep -q '"issue_severity": "HIGH"' bandit-results.json; then
            echo "High severity issues found"
            exit 1
          fi
